platform :ios, '13.0'

def firebase_shared_pods
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
end

target 'newsapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for newsapp

  # Moya
  pod 'Moya', '~> 15.0'

  # Download Image
  pod 'Kingfisher', '~> 7.0'

  # Firebase
  firebase_shared_pods

end
